# Generated by Django 5.2 on 2025-04-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
