# Generated by Django 5.2 on 2025-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tag_project_visible_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
