# Generated by Django 5.2 on 2025-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
