# Generated by Django 5.2 on 2025-04-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_tag_unique_main_tag_per_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_main_tag_per_category',
        ),
        migrations.AddField(
            model_name='category',
            name='main_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category', to='portfolio.tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portfolio.category'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_tag', True)), fields=('category', 'is_main_tag'), name='unique_main_tag_per_category'),
        ),
    ]
