# Generated by Django 5.2 on 2025-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_tag_unique_main_tag_per_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_main_tag',
            field=models.BooleanField(default=False),
        ),
    ]
