# Generated by Django 5.2 on 2025-04-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_tag_unique_main_tag_per_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_main_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_main_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_tag', to='portfolio.category'),
        ),
    ]
