# Generated by Django 5.2 on 2025-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
