# Generated by Django 5.2 on 2025-04-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_lower_name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='is_main_key',
            new_name='is_category_tag',
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_main_key',
        ),
        migrations.RemoveField(
            model_name='category',
            name='visible',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('category', 'is_category_tag'), ('name', 'category')},
        ),
    ]
